#!/bin/bash

NAME="xeniro-snapscale-explorer"

clean(){
  docker ps -a | grep $NAME | awk '{print $1 }'|xargs docker stop
  docker ps -a | grep $NAME | awk '{print $1 }'|xargs docker rm
  docker images | grep $NAME | awk '{print $3 }'|xargs docker rmi
}

build(){
  docker build -t $NAME .
}

run(){
  docker run -itd \
  -p 81:80 \
  --name $NAME $NAME
}

bash(){
  docker exec -itd $NAME /bin/bash
}

case "$1" in
  clean)
    clean
    ;;
  build)
    build
    ;;
  run)
    run
    ;;
  bash)
    bash
    ;;
  *)
    clean
    build
    run
    ;;
esac
