steps:

  - id: docker build
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/ss-explorer:$COMMIT_SHA', '-t', 'asia.gcr.io/$PROJECT_ID/ss-explorer:latest', '--cache-from', 'asia.gcr.io/$PROJECT_ID/ss-explorer:latest', '-f', 'Dockerfile', '.']
  images: ['asia.gcr.io/$PROJECT_ID/ss-explorer:$COMMIT_SHA']
  images: ['asia.gcr.io/$PROJECT_ID/ss-explorer:latest']